on: create
name: Deploy to docker hub
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build
      uses: actions/docker/cli@master
      with:
        args: build -t uwitedm/atlantis .
    - name: Docker Tag
      uses: actions/docker/tag@master
      with:
        args: uwitedm/atlantis uwitedm/atlantis --no-sha --no-latest
    - name: Docker push
      uses: actions/docker/cli@master
      if: github.event.ref_type == 'tag'
      with:
        args: push uwitedm/atlantis
