on:
  release:
    types: [created]
name: Deploy to docker hub
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login hub.docker.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Docker Build
      run: docker build -t atlantis .
    - name: Docker Tag
      run: docker tag atlantis uwitedm/atlantis --no-sha --no-latest
    - name: Docker push
      run: docker push uwitedm/atlantis