on:
  pull_request:
    types: [opened,synchronize]
name: Docker build
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build
      run: docker build -t uw-it-edm/atlantis .
